[[permission]]
identifier = "allow-all-app-commands"
description = "Allow all custom application commands"
commands.allow = [
    "get_cards",
    "add_card",
    "edit_card",
    "delete_card",
    "review_card",
    "get_reminder_card",
    "get_random_card",
    "get_timer_config",
    "set_timer_config",
    "get_next_trigger_time",
    "trigger_reminder_manually",
    "get_window_label",
    "close_reminder_window"
]
